#!/usr/bin/env python3
"""
Generate a demo ``edge-metadata/`` folder for any dataset that has edges.

Why this exists
---------------
The ``edge-metadata/`` convention lets a user annotate cell pairs — a call, a
confidence, a review flag — without regenerating ``edges.parquet`` from R. It is
easy to describe and hard to appreciate until you can click an edge and see the
annotation, so every bundled dataset gets one.

What it writes, and how honest each column is
---------------------------------------------
Three of the four columns are **derived from the edge data itself**, so they carry
real information and are reproducible from the parquet:

  interaction_class   homotypic / heterotypic, from sending_type vs receiving_type,
                      or autocrine / paracrine when the edge file has no cell-type
                      columns. Not a column of edges.parquet, so it genuinely adds
                      something, but it is a restatement of that file rather than
                      a new measurement.
  score_tier          low / mid / high, by tercile of the edge's summed score.
  score_percentile    0-100, the edge's rank by summed score. Continuous, so the
                      edge colour-by has a gradient and clamp sliders to exercise
                      — every other column here is categorical.

One is **invented**, and is named so that it cannot be mistaken for anything else:

  demo_review_flag    reviewed / unreviewed, assigned by a seeded hash of the edge
                      id. It exists purely to give the categorical edge filter and
                      the edge colour-by something to demonstrate.

Every folder also gets a README.md saying the same thing, because a stray CSV of
plausible-looking annotations sitting next to real data is a hazard: someone will
eventually read ``score_tier: high`` on a real kidney section as an analysis
result. Nothing here is an analysis result.

Usage
-----
    python make_edge_metadata.py                       # every dataset with edges
    python make_edge_metadata.py --dataset visium_tiny
    python make_edge_metadata.py --force               # overwrite existing folders

Writes <dataset>/edge-metadata/{example_annotations.csv, README.md}.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

import pandas as pd

# Deterministic, so re-running never churns the file or the golden baseline.
SEED = "tissueplex-demo"

README = """# edge-metadata/ — generated demo annotations

**Not analysis output.** Generated by `sample_data/make_edge_metadata.py`;
reproduce with:

```bash
python sample_data/make_edge_metadata.py --dataset {dataset} --force
```

This folder exists so the `edge-metadata/` feature has something to show on every
bundled dataset — the columns appear in the edge colour-by dropdown, in the edge
filter, and as an *Annotations* block when you click an edge.

| Column | Where it comes from |
|---|---|
| `interaction_class` | Derived from the edge file: {class_basis}. |
| `score_tier` | Derived from the edge file: tercile of the edge's summed score. |
| `score_percentile` | Derived from the edge file: percentile rank of the summed score. The one continuous column. |
| `demo_review_flag` | **Invented.** A seeded hash of the edge id, nothing more. |

The first three restate `edges.parquet` in a form it does not itself carry, so they
are reproducible and true to the data. The last is fabricated and named to make
that obvious. Do not read biology into any of it.
"""


def edge_sources(dataset: Path) -> list[Path]:
    """Every edge parquet for a dataset: the legacy top-level file and edges/."""
    out = []
    top = dataset / "edges.parquet"
    if top.exists():
        out.append(top)
    sub = dataset / "edges"
    if sub.is_dir():
        out.extend(sorted(sub.glob("*.parquet")))
    return out


def build(dataset: Path, force: bool) -> str | None:
    sources = edge_sources(dataset)
    if not sources:
        return None
    out_dir = dataset / "edge-metadata"
    if out_dir.exists() and not force:
        return f"skipped (already has edge-metadata/, use --force)"

    # Annotations are keyed on `edge` and apply across every edge source in the
    # dataset — they describe cell pairs, which belong to the tissue rather than
    # to one scoring run. So pool the edge ids from all sources.
    import pyarrow.parquet as pq

    want = ["edge", "score", "is_autocrine", "sending_type", "receiving_type"]
    frames = []
    for src in sources:
        # Read only the columns that exist, and only those: a real edge file is
        # millions of rows, so pulling all sixteen columns to use four is waste.
        take = [c for c in want if c in set(pq.read_schema(src).names)]
        if "edge" not in take:
            continue
        frames.append(pd.read_parquet(src, columns=take))
    if not frames:
        return "skipped (no `edge` column in any edge source)"

    df = pd.concat(frames, ignore_index=True)
    df = df[df["edge"].notna()]
    if df.empty:
        return "skipped (no edges)"

    # One row per edge. Sum the score so the tier reflects the whole edge, not a
    # single LRM row.
    agg = {"score": "sum"} if "score" in df.columns else {}
    for c in ("is_autocrine", "sending_type", "receiving_type"):
        if c in df.columns:
            agg[c] = "first"
    grouped = df.groupby("edge", as_index=False).agg(agg) if agg \
        else df[["edge"]].drop_duplicates()

    # ── interaction_class ────────────────────────────────────────────────────
    has_types = {"sending_type", "receiving_type"} <= set(grouped.columns) and \
        grouped["sending_type"].notna().any()
    if has_types:
        grouped["interaction_class"] = [
            "homotypic" if s == r else "heterotypic"
            for s, r in zip(grouped["sending_type"], grouped["receiving_type"])
        ]
        class_basis = "`homotypic` when sending_type == receiving_type, else `heterotypic`"
    elif "is_autocrine" in grouped.columns:
        grouped["interaction_class"] = [
            "autocrine" if bool(a) else "paracrine" for a in grouped["is_autocrine"]
        ]
        class_basis = ("`autocrine` / `paracrine` from the is_autocrine flag "
                       "(this edge file carries no cell-type columns)")
    else:
        grouped["interaction_class"] = "unclassified"
        class_basis = "constant — this edge file carries neither cell types nor is_autocrine"

    # ── score_tier ───────────────────────────────────────────────────────────
    if "score" in grouped.columns and grouped["score"].notna().any():
        try:
            grouped["score_tier"] = pd.qcut(
                grouped["score"].rank(method="first"), 3,
                labels=["low", "mid", "high"]
            ).astype(str)
        except ValueError:          # too few distinct values to cut into three
            grouped["score_tier"] = "mid"
        grouped["score_percentile"] = (
            grouped["score"].rank(pct=True) * 100).round(2)
    else:
        grouped["score_tier"] = "unscored"
        grouped["score_percentile"] = 0.0

    # ── demo_review_flag — invented, and named to say so ─────────────────────
    grouped["demo_review_flag"] = [
        "reviewed" if int(hashlib.sha256((SEED + str(e)).encode()).hexdigest(), 16) % 3 == 0
        else "unreviewed"
        for e in grouped["edge"]
    ]

    out_dir.mkdir(parents=True, exist_ok=True)
    out = grouped[["edge", "interaction_class", "score_tier",
                   "score_percentile", "demo_review_flag"]]
    # index=False plus an explicit `edge` column: the loader resolves the key as
    # an explicit `edge` column first, so this needs no unnamed rowname column.
    out.to_csv(out_dir / "example_annotations.csv", index=False)
    (out_dir / "README.md").write_text(
        README.format(dataset=dataset.name, class_basis=class_basis))

    counts = out["interaction_class"].value_counts().to_dict()
    return f"{len(out):>7,} edges  {counts}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", help="one dataset name; default is all with edges")
    ap.add_argument("--root", default=str(Path(__file__).resolve().parent))
    ap.add_argument("--force", action="store_true", help="overwrite existing folders")
    args = ap.parse_args()

    root = Path(args.root)
    targets = [root / args.dataset] if args.dataset else \
        sorted(p for p in root.iterdir() if p.is_dir())

    for d in targets:
        if not d.is_dir():
            print(f"  {d.name}: not a directory")
            continue
        result = build(d, args.force)
        if result is not None:
            print(f"  {d.name:26s} {result}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
